// Copyright 2017 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef GATT_DB_H
#define GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_numOfMotors                     19
#define gattdb_batVol                          23
#define gattdb_pwm1Percentage                  27
#define gattdb_pwm2Percentage                  30
#define gattdb_pwm3Percentage                  33
#define gattdb_pwm4Percentage                  36
#define gattdb_ota_control                     40

#endif
